// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Seed provides a mock function with given fields: ctx, addr, port, seedPartial
func (_m *Server) Seed(ctx context.Context, addr string, port int, seedPartial bool) {
	_m.Called(ctx, addr, port, seedPartial)
}
